name: MLflow Project Training - ADVANCE (Docker Hub)

# ===== TRIGGER =====
on:
  # Manual trigger
  workflow_dispatch:
  
  # Trigger saat push ke main
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
      - 'Dockerfile'
      - '.github/workflows/mlflow-training.yml'
  
  # Scheduled trigger (setiap hari jam 12:00 UTC)
  schedule:
    - cron: '0 12 * * *'

# ===== JOBS =====
jobs:
  mlflow-training:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Step 2: Setup Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Step 3: Install dependencies
      - name: Install MLflow and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install -r requirements.txt
          echo "✅ Dependencies installed"
      
      # Step 4: Setup MLflow tracking
      - name: Setup MLflow tracking
        run: |
          mkdir -p mlruns
          mkdir -p artifacts
          echo "✅ Directories created"
      
      # Step 5: Run MLflow Project
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . -m local --no-conda
          echo "✅ MLflow Project executed"
        env:
          MLFLOW_TRACKING_URI: file:///github/workspace/mlruns
      
      # Step 6: Collect artifacts
      - name: Collect artifacts
        run: |
          echo "✅ Collecting artifacts..."
          cp -r mlruns artifacts/ || true
          find artifacts/ -type f
      
      # Step 7: Upload artifacts to GitHub
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-training-artifacts
          path: artifacts/
          retention-days: 30
      
      # Step 8: Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Step 9: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      # Step 10: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-classification:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-classification:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # Step 11: Commit artifacts to repo
      - name: Commit artifacts to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          
          git add artifacts/ mlruns/ || true
          
          git commit -m "🤖 Auto: Update MLflow artifacts & Docker image - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          git push origin main || echo "Push skipped"
      
      # Step 12: Summary
      - name: Job Summary
        run: |
          echo "## ✅ MLflow Project Training Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp**: $(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "**Model Training**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "**Artifacts Uploaded**: ✅ GitHub" >> $GITHUB_STEP_SUMMARY
          echo "**Docker Image Built**: ✅ Pushed to Docker Hub" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Docker Hub Details" >> $GITHUB_STEP_SUMMARY
          echo "- Image: \`${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-classification:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: https://hub.docker.com/r/${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-classification" >> $GITHUB_STEP_SUMMARY
          echo "- Commit Tag: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Generated Artifacts:" >> $GITHUB_STEP_SUMMARY
          echo "- Model file (pkl)" >> $GITHUB_STEP_SUMMARY
          echo "- Confusion Matrix (png)" >> $GITHUB_STEP_SUMMARY
          echo "- Feature Importance (png)" >> $GITHUB_STEP_SUMMARY
          echo "- Classification Report (txt)" >> $GITHUB_STEP_SUMMARY
          echo "- MLflow runs data" >> $GITHUB_STEP_SUMMARY